import express from 'express';
import cors from 'cors';
import { createProduct, getNextShopBarcode, getProduct, listPriceHistory, listProducts, updateProduct, updateProductPrice } from './repositories/productRepository.js';
import { createBrand, listCategories, listSubcategories, listBrands, listUnits, listSuppliers } from './repositories/lookupRepository.js';
import { db } from './database/db.js';
import { adjustStock, batches, listInventory, movements, stockIn, stockOut, summary, updateMinimum } from './repositories/inventoryRepository.js';
import { finalize, getBill, listBills, lookup as lookupBillingProduct, searchProducts } from './repositories/billingRepository.js';

export const app = express();
app.use(cors());
app.use(express.json());
const ok = (data: unknown) => ({ success: true, data });
const fail = (message: string, code?: string) => ({ success: false, ...(code ? { code } : {}), message });
const canManageProducts = (req: express.Request) => ['OWNER', 'ADMIN'].includes(String(req.header('x-user-role') || '').toUpperCase());
const inventoryRole = (req: express.Request) => String(req.header('x-user-role') || '').toUpperCase();
const canManageInventory = (req: express.Request) => ['OWNER', 'ADMIN'].includes(inventoryRole(req));

app.get('/api/health', (_req, res) => {
  try {
    db.prepare('SELECT 1').get();
    return res.json({ status: 'ok', database: 'connected' });
  } catch {
    return res.status(500).json({ status: 'error', database: 'disconnected' });
  }
});

app.get('/api/products/next-shop-barcode', (req, res) => { if (!canManageProducts(req)) return res.status(403).json(fail('You do not have permission to generate shop barcodes.')); return res.json(ok({ barcode: getNextShopBarcode(), identifierType: 'INTERNAL_BARCODE' })); });
app.get('/api/products', (req, res) => res.json(ok(listProducts(req.query as Record<string, string>))));
app.get('/api/products/:id', (req, res) => { const product = getProduct(Number(req.params.id)); if (!product) return res.status(404).json(fail('Product not found')); return res.json(ok(product)); });
app.get('/api/products/:id/price-history', (req, res) => res.json(ok(listPriceHistory(Number(req.params.id)))));
app.post('/api/products', (req, res) => { if (!canManageProducts(req)) return res.status(403).json(fail('You do not have permission to create products.')); try { const product = createProduct(req.body); return res.status(201).json(ok(product)); } catch (error) { const errorText = String(error); const duplicateIdentifier = errorText.includes('product_identifiers') || errorText.includes('identifier_value'); const duplicate = errorText.includes('UNIQUE'); const message = duplicateIdentifier ? 'This barcode is already assigned to another product.' : errorText.includes('IDENTIFIER_REQUIRED') ? 'A barcode is required for a manufacturer product.' : errorText.includes('INVALID_IDENTIFIER') ? 'Barcode format is not valid for the selected identifier type.' : errorText.includes('SHOP_IDENTIFIER_MANAGED') ? 'Shop barcodes are generated by the server.' : duplicate ? 'SKU or product code already exists.' : 'Unable to create product.'; return res.status(duplicate ? 409 : 400).json(fail(message, duplicateIdentifier ? 'DUPLICATE_IDENTIFIER' : undefined)); } });
app.put('/api/products/:id', (req, res) => { if (!canManageProducts(req)) return res.status(403).json(fail('You do not have permission to update products.')); try { const product = updateProduct(Number(req.params.id), { ...req.body, changedBy: req.header('x-user-role') || 'SYSTEM' }); if (!product) return res.status(404).json(fail('Product not found')); return res.json(ok(product)); } catch (error) { const message = String(error).includes('SELLING_PRICE_EXCEEDS_MRP') ? 'Selling price cannot be greater than MRP.' : String(error).includes('INVALID_PRICE') ? 'Prices must be zero or greater.' : String(error).includes('UNIQUE') ? 'SKU or product code already exists.' : 'Unable to update product.'; return res.status(400).json(fail(message)); } });
app.patch('/api/products/:id/price', (req, res) => { if (!canManageProducts(req)) return res.status(403).json(fail('You do not have permission to update product prices.')); try { const product = updateProductPrice(Number(req.params.id), { ...req.body, changedBy: req.header('x-user-role') || 'SYSTEM' }); if (!product) return res.status(404).json(fail('Product not found')); return res.json(ok(product)); } catch (error) { const message = String(error).includes('SELLING_PRICE_EXCEEDS_MRP') ? 'Selling price cannot be greater than MRP.' : String(error).includes('INVALID_PRICE') ? 'Prices must be zero or greater.' : 'Unable to update product price.'; return res.status(400).json(fail(message)); } });
app.delete('/api/products/:id', (req, res) => { if (!canManageProducts(req)) return res.status(403).json(fail('You do not have permission to deactivate products.')); const result = db.prepare("UPDATE products SET status='INACTIVE', updated_at=? WHERE id=?").run(new Date().toISOString(), Number(req.params.id)); if (!result.changes) return res.status(404).json(fail('Product not found')); return res.json(ok({ message: 'Product deactivated successfully.' })); });

app.get('/api/categories', (_req, res) => res.json(ok(listCategories())));
app.get('/api/subcategories', (_req, res) => res.json(ok(listSubcategories())));
app.get('/api/brands', (_req, res) => res.json(ok(listBrands())));
app.post('/api/brands', (req, res) => {
  if (!['OWNER', 'ADMIN'].includes(String(req.header('x-user-role') || '').toUpperCase())) return res.status(403).json(fail('You do not have permission to create brands.'));
  try { return res.status(201).json(ok(createBrand(req.body))); }
  catch (error) { const message = String(error).includes('Brand already exists') ? 'Brand already exists.' : error instanceof Error ? error.message : 'Unable to create brand. Please try again.'; return res.status(message === 'Brand already exists.' ? 409 : 400).json(fail(message)); }
});
app.get('/api/units', (_req, res) => res.json(ok(listUnits())));
app.get('/api/suppliers', (_req, res) => res.json(ok(listSuppliers())));

app.get('/api/products/lookup/:value', (req, res) => {
  const value = req.params.value.trim();
  const found = db.prepare(`SELECT p.id, p.product_code AS productCode, p.name_english AS nameEnglish, p.name_tamil AS nameTamil, p.sku, b.name AS brand, c.name AS category, p.mrp, p.selling_price AS sellingPrice
    FROM product_identifiers pi
    JOIN products p ON p.id = pi.product_id
    LEFT JOIN brands b ON b.id = p.brand_id
    LEFT JOIN categories c ON c.id = p.category_id
    WHERE pi.identifier_value = ?`).get(value) as { id: number; productCode: string; nameEnglish: string; nameTamil: string; sku: string; brand?: string; category?: string; mrp: number; sellingPrice: number } | undefined;
  if (!found) return res.json({ exists: false });
  return res.json({ exists: true, product: found });
});

app.get('/api/identifiers/:value', (req, res) => res.redirect(`/api/products/lookup/${encodeURIComponent(req.params.value)}`));

app.get('/api/pos/products/lookup/:value', (req, res) => { const product = lookupBillingProduct(req.params.value); if (!product) return res.status(404).json(fail('Product not found.')); return res.json(ok(product)); });
app.get('/api/pos/products/search', (req, res) => res.json(ok(searchProducts(String(req.query.q || '')))));
app.post('/api/bills', (req, res) => { try { return res.status(201).json(ok(finalize({ ...req.body, cashierId: inventoryRole(req) || 'CASHIER' }))); } catch (error) { return res.status(400).json(fail(billingMessage(error))); } });
app.get('/api/bills', (req, res) => res.json(ok(listBills(String(req.query.search || '')))));
app.get('/api/bills/:id', (req, res) => { const bill = getBill(Number(req.params.id)); if (!bill) return res.status(404).json(fail('Bill not found.')); return res.json(ok(bill)); });

app.get('/api/inventory/summary', (_req, res) => res.json(ok(summary())));
app.get('/api/inventory', (req, res) => res.json(ok(listInventory(req.query as Record<string, string>))));
app.get('/api/inventory/products', (req, res) => res.json(ok(listInventory(req.query as Record<string, string>))));
app.get('/api/inventory/movements', (req, res) => res.json(ok(movements(Number(req.query.limit) || 50))));
app.get('/api/inventory/products/:id/batches', (req, res) => { try { return res.json(ok(batches(Number(req.params.id)))); } catch { return res.status(404).json(fail('Product not found.')); } });
app.post('/api/inventory/stock-in', (req, res) => { if (!canManageInventory(req)) return res.status(403).json(fail('Unauthorized inventory action.')); try { return res.status(201).json(ok(stockIn({ ...req.body, createdBy: inventoryRole(req) }))); } catch (error) { return res.status(400).json(fail(inventoryMessage(error))); } });
app.post('/api/inventory/stock-out', (req, res) => { if (!canManageInventory(req)) return res.status(403).json(fail('Unauthorized inventory action.')); try { return res.status(201).json(ok(stockOut({ ...req.body, createdBy: inventoryRole(req) }))); } catch (error) { return res.status(400).json(fail(inventoryMessage(error))); } });
app.post('/api/inventory/adjust', (req, res) => { if (!canManageInventory(req)) return res.status(403).json(fail('Unauthorized inventory action.')); try { return res.status(201).json(ok(adjustStock({ ...req.body, createdBy: inventoryRole(req) }))); } catch (error) { return res.status(400).json(fail(inventoryMessage(error))); } });
app.patch('/api/inventory/products/:id/minimum', (req, res) => { if (!canManageInventory(req)) return res.status(403).json(fail('Unauthorized inventory action.')); try { return res.json(ok(updateMinimum(Number(req.params.id), Number(req.body.minimumQuantity)))); } catch (error) { return res.status(400).json(fail(inventoryMessage(error))); } });

function inventoryMessage(error: unknown) {
  const code = String(error);
  if (code.includes('PRODUCT_NOT_FOUND')) return 'Product not found.';
  if (code.includes('PRODUCT_INACTIVE')) return 'Product is inactive.';
  if (code.includes('INSUFFICIENT_STOCK')) return 'Insufficient stock.';
  if (code.includes('INVALID_QUANTITY')) return 'Quantity must be greater than zero.';
  if (code.includes('INVALID_PRICE')) return 'Purchase price must be zero or greater.';
  if (code.includes('INVALID_DATE')) return 'Invalid expiry or manufacturing date.';
  return 'Unable to update inventory.';
}

function billingMessage(error: unknown) {
  const code = String(error);
  if (code.includes('EMPTY_CART')) return 'Add at least one product to the bill.';
  if (code.includes('PRODUCT_NOT_FOUND')) return 'Product not found.';
  if (code.includes('INSUFFICIENT_STOCK')) return 'Insufficient stock.';
  if (code.includes('INVALID_QUANTITY')) return 'Quantity must be greater than zero.';
  if (code.includes('INVALID_DISCOUNT')) return 'Invalid discount.';
  return 'Unable to finalize bill.';
}

app.use((_error: unknown, _req: express.Request, res: express.Response, _next: express.NextFunction) => res.status(500).json(fail('Internal server error.')));
